---
jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - aggregate: 
    - get: cf-mta-deploy-service-git-repo
      trigger: false #temp for debug
    - get: cf-mta-cli-plugin-git-repo
      trigger: true
  - task: prepare-docker-context
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository:  cloudfoundry/cli-ci}
      run:
        path: 'bash'
#        args: ["oq-test-git-repo/oq.tests/pipeline/generate_timestamp.sh","ts/tag"]
        args: ["oq-test-git-repo/oq.tests/pipeline/prepare-docker-context.sh","cf-mta-cli-plugin-git-repo","github.com/SAP/cf-mta-plugin","oq-test-git-repo/oq.tests","output/context"]
      inputs:
      - name: cf-mta-deploy-service-git-repo
        path: "oq-test-git-repo"
      - name: cf-mta-cli-plugin-git-repo
        path: "cf-mta-cli-plugin-git-repo"
      outputs:
      - name: "docker-context"
        path: "output"
  - put: test-environment-image
    params:
      build: docker-context/context
      tag_as_latest: true
- name: run-sanity-check-test
  plan:
  - aggregate: 
    - get: cf-mta-deploy-service-git-repo
      trigger: true #should we run the OQs for each change in the test's code?
      #passed: [build-docker-image]
#    - get: cf-mta-cli-plugin-git-repo
#      trigger: false #should we run the OQs for each change in the client?
#      passed: [build-docker-image]
    - get: 15m  #Run every 15 minutes
      trigger: true
    - get: test-environment-image
      trigger: false # if true, it will run whenever a new test content image is created :)
      passed: [build-docker-image]
      params:
        tag: latest
  - task: test-substep-1
    image: test-environment-image
    config:
      platform: linux
      inputs:
      - name: cf-mta-deploy-service-git-repo
        path: "oq-test-git-repo"
      run:
        path: 'bash'
        args:
        - -c
        - |
          cp -rv oq-test-git-repo/oq.tests/test_scenarios /workspace/
          cp -rv oq-test-git-repo/oq.tests/test_scripts /workspace/
          cp -rv oq-test-git-repo/oq.tests/*.sh /workspace/ 
          bash -x "/workspace/test_scenarios/CF Tests/Sanity Check/run.sh"
          
      params:
        TEST_WORKING_DIRECTORY: "/workspace"
        DEFAULT_ORG: ((DEFAULT_ORG))
        DEFAULT_SPACE: ((DEFAULT_SPACE))
        DEPLOY_SERVICE_HOST: ((DEPLOY_SERVICE_HOST))
        DEPLOY_SERVICE_URL: ((DEPLOY_SERVICE_URL))
        ORG_NAME: ((ORG_NAME))
        SPACE_NAME: ((SPACE_NAME))
        RT_API_ENDPOINT: ((RT_API_ENDPOINT))
        USER_NAME: ((USER_NAME))
        USER_PASS: ((USER_PASS))
    on_failure:
      put: slack-alert
      params:
        text: |
          Oops, $BUILD_JOB_NAME OQ test failed:
          http://((ci-host))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          http://((ci-host))/builds/$BUILD_ID
- name: run-bg-deploy-with-content-change-test
  plan:
  - aggregate: 
    - get: cf-mta-deploy-service-git-repo
      trigger: true
    - get: test-environment-image
      trigger: false # temporarily disable let's run whenever a new test content image is created :)
      passed: [build-docker-image]
      params:
        tag: latest
  - task: test-substep-1
    image: test-environment-image
    config:
      platform: linux
      inputs:
      - name: cf-mta-deploy-service-git-repo
        path: "oq-test-git-repo"
      run:
      
        path: 'bash'
        args:
        - -c
        - |
          cp -rv oq-test-git-repo/oq.tests/test_scenarios /workspace/
          cp -rv oq-test-git-repo/oq.tests/test_scripts /workspace/
          cp -rv oq-test-git-repo/oq.tests/*.sh /workspace/ 
          bash "/workspace/test_scenarios/CF Tests/Blue Green with Content Change/run.sh"
      params:
        TEST_WORKING_DIRECTORY: "/workspace"
        DEFAULT_ORG: ((DEFAULT_ORG))
        DEFAULT_SPACE: ((DEFAULT_SPACE))
        DEPLOY_SERVICE_HOST: ((DEPLOY_SERVICE_HOST))
        DEPLOY_SERVICE_URL: ((DEPLOY_SERVICE_URL))
        ORG_NAME: ((ORG_NAME))
        SPACE_NAME: ((SPACE_NAME))
        RT_API_ENDPOINT: ((RT_API_ENDPOINT))
        USER_NAME: ((USER_NAME))
        USER_PASS: ((USER_PASS))
    on_failure:
      put: slack-alert
      params:
        text: |
          Oops, $BUILD_JOB_NAME OQ test failed:
          http://((ci-host))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          http://((ci-host))/builds/$BUILD_ID

- name: failing-with-notification-test
  plan:
  - aggregate: 
    - get: test-environment-image
      trigger: false # temporarily disable let's run whenever a new test content image is created :)
      passed: [build-docker-image]
      params:
        tag: latest
  - task: test-substep-1
    image: test-environment-image
    config:
      platform: linux
      run:
        path: 'bash'
        args: ["asdfsad;lkfjs"]
    on_failure:
      put: slack-alert
      params:
        text: |
          Oops, $BUILD_JOB_NAME OQ test failed:
          http://((ci-host))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          http://((ci-host))/builds/$BUILD_ID
resources:
- name: cf-mta-deploy-service-git-repo
  type: git
  source:
    uri: https://github.com/ddonchev/cf-mta-deploy-service.git
    branch: oq_poc
    skip_ssl_verification: true
- name: cf-mta-cli-plugin-git-repo
  type: git
  source:
     uri: https://github.com/ddonchev/cf-mta-plugin.git
     branch: master
     skip_ssl_verification: true
- name: test-environment-image
  type: docker-image
  source:
     repository: registry:5000/mta-test-image
     insecure_registries: [ "registry:5000" ]
- name: 15m
  type: time
  source: {interval: 15m}
- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-webhook))

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest