---
jobs:
- name: build-docker-image
#  public: true
  serial: true
  plan:
  - get: oq-tests-git-repo
    trigger: true
  - task: create-timestamp
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: 'bash'
        args: ["oq-test-git-repo/oq.tests/pipeline/generate_timestamp.sh","ts/tag"]
      inputs:
      - name: oq-tests-git-repo
        path: "oq-test-git-repo"
      outputs:
      - name: timestamp
        path: "ts"
  - put: test-environment-image
    params:
      build: oq-tests-git-repo/oq.tests
      tag: timestamp/tag
- name: run-test
  plan:
  - get: test-environment-image
    trigger: true
  - task: test-substep-1
    image: test-environment-image
    config:
      platform: linux
      run:
        path: 'bash'
        args: ["/workspace/test_scenarios/CF Tests/CF Canary Tests/Sanity Check/run.sh"]
      params:
        DEFAULT_ORG: ((DEFAULT_ORG))
        DEFAULT_SPACE: ((DEFAULT_SPACE))
        DEPLOY_SERVICE_HOST: ((DEPLOY_SERVICE_HOST))
        DEPLOY_SERVICE_URL: ((DEPLOY_SERVICE_URL))
        ORG_NAME: ((ORG_NAME))
        SPACE_NAME: ((SPACE_NAME))
        RT_API_ENDPOINT: ((RT_API_ENDPOINT))
        USER_NAME: ((USER_NAME))
        USER_PASS: ((USER_PASS))
resources:
- name: oq-tests-git-repo
  type: git
  source:
    uri: https://github.com/ddonchev/cf-mta-deploy-service.git
    branch: oq_poc
    skip_ssl_verification: true

- name: test-environment-image
  type: docker-image
  source:
     repository: 192.168.100.4:5000/mta-test-image
     insecure_registries: [ "192.168.100.4:5000" ]
